### ISSUE TITLE
"técnica"

### ISSUE THREAD

**Issue by ghost** [davimoreiraa/Adopet#2]

**Comment by davimoreiraa** [comment]
usar como? como eu coloquei no readme, o design nao foi feito por mim. Mas o código foi.

**Comment by davimoreiraa** [comment]
mas me fala melhor como vc quer usar

**Comment by davimoreiraa** [comment]
poxa cara, nao queria ser chato, mas nao curti muito a ideia

**Comment by davimoreiraa** [comment]
quando disse q nao curti muito estava me referindo a ideia, nao da sua pergunta. mas n tem problema nenhum fazer um codigo baseando-se no design, pode ate pegar as imagens, elas nao sao de minha autoria mesmo. mas o codigo eu nao quero que copie

**Comment by davimoreiraa** [comment]
pode usar como base, tudo bem
